-- GameState schema, v1.
--
-- Plain SQL on purpose. No migration framework yet -- while the schema is still
-- moving weekly, a stack of hand-numbered files you can read top to bottom is
-- clearer than Alembic's autogenerated churn. When the shape stabilises and we
-- need to evolve a live database without dropping it, that is the moment to
-- adopt Alembic (see the note at the foot of this file).
--
-- Apply with:  psql "$DATABASE_URL" -f migrations/0001_initial_schema.sql
--
-- Design decisions live in docs/decisions/0005-database-schema.md. The short
-- version of the three that shaped everything:
--   1. Predictions are APPEND-ONLY and versioned by run -> full forecast history.
--   2. Margin is stored as a PMF over integers -> key numbers represented exactly.
--   3. All instants are TIMESTAMPTZ -> the leakage discipline needs real time.


-- ---------------------------------------------------------------------------
-- games : one row per game. The spine everything else hangs off.
-- ---------------------------------------------------------------------------
CREATE TABLE games (
    game_id      TEXT        PRIMARY KEY,          -- nflverse id, e.g. 2024_01_BAL_KC
    season       SMALLINT    NOT NULL,
    week         SMALLINT    NOT NULL,

    -- The single most safety-critical column in the database. Every feature is
    -- required to be computable strictly before this instant. TIMESTAMPTZ, not
    -- DATE and not a naive timestamp: a Thursday-night game and a Sunday-1pm
    -- game are different information cutoffs, and storing them without a zone
    -- is how a late kickoff silently leaks into an earlier prediction.
    kickoff_at   TIMESTAMPTZ NOT NULL,

    home_team    TEXT        NOT NULL,
    away_team    TEXT        NOT NULL,

    -- Context that conditions the model. Nullable because it is unknown for
    -- games far in the future (a dome is fixed, but a retractable roof's state
    -- on game day is not).
    roof         TEXT,
    surface      TEXT,

    -- Results. NULL until the game is played -- which is exactly how we tell
    -- "predictable future" from "scored past" without a separate status column.
    home_score   SMALLINT,
    away_score   SMALLINT,

    CONSTRAINT teams_differ CHECK (home_team <> away_team),
    CONSTRAINT scores_paired CHECK (
        (home_score IS NULL) = (away_score IS NULL)   -- both set, or both null
    )
);

CREATE INDEX games_season_week ON games (season, week);
CREATE INDEX games_kickoff     ON games (kickoff_at);


-- ---------------------------------------------------------------------------
-- market_lines : the betting market over time. Its OWN table, deliberately.
-- ---------------------------------------------------------------------------
-- Lines move. The opening line and the closing line are different pieces of
-- information, and the movement between them is itself signal. Folding a single
-- "spread" column into games would throw all of that away permanently. One row
-- per (game, book, capture) preserves the whole trajectory.
CREATE TABLE market_lines (
    id             BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    game_id        TEXT        NOT NULL REFERENCES games (game_id),
    book           TEXT        NOT NULL,            -- sportsbook / source
    captured_at    TIMESTAMPTZ NOT NULL,            -- when we OBSERVED this line

    spread         REAL,                            -- home spread, e.g. -3.0
    total          REAL,
    home_moneyline INTEGER,
    away_moneyline INTEGER,

    UNIQUE (game_id, book, captured_at)
);

CREATE INDEX market_lines_game ON market_lines (game_id, captured_at);


-- ---------------------------------------------------------------------------
-- model_runs : the audit anchor. Every prediction points back to one of these.
-- ---------------------------------------------------------------------------
-- This is what makes results reproducible. A prediction is meaningless without
-- knowing which code and which data produced it. git_sha ties a row to an exact
-- commit; trained_through records the leakage boundary; the params capture the
-- knobs. Six months on, "why did we say 62% that week" is answerable.
CREATE TABLE model_runs (
    run_id          BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    git_sha         TEXT        NOT NULL,           -- exact commit of the code
    model_version   TEXT        NOT NULL,           -- human label, e.g. "margin-normal-v1"
    feature_set     TEXT[]      NOT NULL,           -- which features were used

    -- The leakage boundary for the whole run: only data before this instant
    -- was allowed in. Mirrors kickoff_at's role at the row level.
    trained_through TIMESTAMPTZ NOT NULL,

    half_life       REAL,                           -- recency weighting, NULL = none
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes           TEXT
);

CREATE INDEX model_runs_created ON model_runs (created_at DESC);


-- ---------------------------------------------------------------------------
-- predictions : APPEND-ONLY. One row per (run, game). Never UPDATE-d.
-- ---------------------------------------------------------------------------
-- Because the user chose full forecast history, we never overwrite. Tuesday's
-- prediction and Saturday's prediction for the same game are two rows under two
-- runs. The site reads them as a trajectory; nothing is lost to an UPDATE.
CREATE TABLE predictions (
    run_id       BIGINT      NOT NULL REFERENCES model_runs (run_id),
    game_id      TEXT        NOT NULL REFERENCES games (game_id),

    -- Distribution summary. mu/sigma are convenient and enough for thresholds
    -- away from key numbers; they do NOT define the distribution on their own.
    mu           REAL        NOT NULL,
    sigma        REAL        NOT NULL,

    -- The distribution itself: P(margin = k) for k in [-60, +60], 121 entries.
    -- Index 0 is margin -60, index 60 is 0, index 120 is +60.
    --
    -- This is the representation that survives the model change we KNOW is
    -- coming. Margins are integers, so a PMF on the lattice reproduces key
    -- numbers (+/-3, +/-7) exactly -- the thing a Normal cannot do (ADR-0004).
    -- Every threshold is a suffix sum over this array: P(margin > 3.5) is just
    -- sum(pmf[64:]). And it is identical whether the numbers came from a
    -- discretised Normal today or from simulation later. ~1 KB/game.
    margin_pmf   REAL[]      NOT NULL,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (run_id, game_id),
    CONSTRAINT pmf_length CHECK (array_length(margin_pmf, 1) = 121)
);

-- "Latest prediction per game" and "this game's whole history" are the two hot
-- read paths. This index serves both.
CREATE INDEX predictions_game_time ON predictions (game_id, created_at DESC);


-- ---------------------------------------------------------------------------
-- calibration : evaluation results per run, sliced. Populated by backtests.
-- ---------------------------------------------------------------------------
-- Aggregate scores hide subgroup bias (ADR-0002: a change that halved home-team
-- bias barely moved aggregate log loss). Storing calibration BY SLICE -- dome
-- vs outdoor, favourite vs dog, early vs late -- is what makes that bias
-- visible, and it is the honest public-facing artifact the site is built around.
CREATE TABLE calibration (
    run_id       BIGINT      NOT NULL REFERENCES model_runs (run_id),
    slice        TEXT        NOT NULL,              -- e.g. "roof=outdoors", "overall"
    bucket       TEXT        NOT NULL,              -- e.g. "0.6-0.8"
    n            INTEGER     NOT NULL,
    predicted    REAL        NOT NULL,              -- mean predicted prob in bucket
    actual       REAL        NOT NULL,              -- observed frequency
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (run_id, slice, bucket)
);


-- ---------------------------------------------------------------------------
-- When to adopt Alembic
-- ---------------------------------------------------------------------------
-- The moment a schema change has to preserve data in a running database. Right
-- now we can drop and recreate freely, so plain files win on readability. Once
-- the site is live with real prediction history, "ALTER TABLE without losing
-- rows" is a versioned-migration problem, and that is Alembic's job. This file
-- becomes migration 0001 in that system with no rewrite.
